//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int NewsFeedPost_ID { get; set; }
        public int User_ID { get; set; }
    }
}
